name: conda-packages

on:
  push:
    branches:
      - main
      - release
      - kairolith
  workflow_dispatch:

jobs:
  conda-packages:
    uses: simbricks/ci-workflows/.github/workflows/conda-packages.yml@v3
    secrets: inherit
